<?php
/**
 * __title__
 * TODO: This code is auto generated by "document_to_views".__copyright____author__
 * __comment__
 */
?>
    <!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>__title__</title>

    <link href="{{ mix('/css/app.css') }}" rel="stylesheet">

</head>
<body>

<main id="__view_id__">
__view_id__
</main>

{{-- Javascript --}}
<script src="{{ mix('/js/app.js') }}"></script>
</body>
</html>
